routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' =>['auth','role:admin']],function(){

    Route::resource('room', 'mRoomController');

});

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];
}

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;
use Illuminate\Support\Facades\Auth;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class User extends Authenticatable implements AuditableContract
{
    use LaratrustUserTrait;
    use Notifiable;
    use Auditable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','photo',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/mBooking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class mBooking extends Model implements AuditableContract
{
    //
    use SoftDeletes;
    use Auditable;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'user_id',
        'room_id',
        'total_person',
        'booking_time',
        'noted',
        'check_in_time',
        'check_out_time',
    ];


    public function get_user(){
        return $this->belongsTo('App\User','user_id','id');
    }

    public function get_room(){
        return $this->belongsTo('App\room','room_id','id');
    }
}

app/mRoom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class mRoom extends Model implements AuditableContract
{
    //
    use SoftDeletes;
    use Auditable;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'room_name',
        'room_capacity',
        'photo',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/mBookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class mBookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/mRoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\mRoomDataTable;
use App\mRoom;
use Session;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class mRoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(mRoomDataTable $dataTable)
    {
        //
        return $dataTable->render('master.room.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('master.room.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $folder = 'images/rooms';
        $uploaded = 0;

        $file = $request->image_pf;

        $filename = $file->getClientOriginalName();
        
        $ext = strtolower($file->getClientOriginalExtension());

        $document = md5($filename. $request->room_name. Carbon::today()->toDateTimeString()).'.'. $ext;

        $upload_path = $file->storeAs($folder, $document);

        $this->validate($request , [
            'room_name'    => 'required|unique:m_rooms,room_name',
            'room_capacity'    => 'required',
        ]);

        $room = mRoom::create([
            'room_name'    => $request->room_name,
            'room_capacity'    => $request->room_capacity,
            'photo' => $upload_path,
        ]);

        Session::flash("flash_notification",[
            "level"     => "success",
            "message"   => "Berhasil menyimpan $room->room_name"
        ]);

        return redirect()->route('room.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/datatable/_delete.blade.php
{!! Form::model($model, ['url' => $delete_url, 'method' => 'delete', 'class' => 'form-inline js-confirm', 'data-confirm' => $confirm_message] ) !!} 
{!! Form::button('<i class="fas fa-trash" aria-hidden="true"></i>', array('type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'data-toggle' => 'tooltip', 'title' => 'Delete')) !!}
{!! Form::close() !!}

resources/views/datatable/_edit.blade.php
{!! Form::model($model, ['url' => $edit_url, 'method' => 'get', 'class' => 'form-inline'] ) !!}
{!! Form::button('<i class="fas fa-edit" aria-hidden="true"></i>', array('type' => 'submit', 'class' => 'btn btn-sm btn-warning', 'data-toggle' => 'tooltip', 'title' => 'Edit')) !!}
{!! Form::close() !!}

resources/views/datatable/_show.blade.php
{!! Form::model($model, ['url' => $show_url, 'method' => 'get', 'class' => 'form-inline'] ) !!}
{!! Form::button('<i class="fas fa-eye" aria-hidden="true"></i>', array('type' => 'submit', 'class' => 'btn btn-sm btn-info', 'data-toggle' => 'tooltip', 'title' => 'Show')) !!}
{!! Form::close() !!}

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'Paperless 4.0')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to Paperless 4.0</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/master/room/_form.blade.php
<div class="row p-t-20">
    <div class="col-md-2">
    <div class="form-group{{ $errors->has('room_name') ? 'has-error': '' }} ">
            {!! Form::label('room_name', 'Room Name', ['class'=>'form-label']) !!}
            {!! Form::text('room_name', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('room_name', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('room_capacity') ? 'has-error': '' }} ">
            {!! Form::label('room_capacity', 'Capacity Room', ['class'=>'form-label']) !!}
            {!! Form::text('room_capacity', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('room_capacity', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group form-float{{ $errors->has('image_pf') ? 'has-error' : '' }}">
        {!! Form::label('image_pf','Room Pic', ['class'=> 'form-label']) !!}
        {!! Form::file('image_pf'); !!}
        {!! $errors->first('image_pf', '<p class="error">:message</p>') !!}
        </div>
    </div>
</div>

{!! Form::submit ('Simpan',['class'=>'btn btn-primary m-b-10 m-l-5']) !!}

resources/views/master/room/create.blade.php
@extends('adminlte::page')

@section('title', 'Plant - Manufacturing 4.0')

@section('content_header')
    <h1>Plant</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Room</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">MASTER</li>
                <li class="breadcrumb-item"><a href="{{ route('room.index') }}">Room</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::open(['url' => route('room.store'),
                    'method' => 'post' ,'files' => 'true' , 'id' => 'form_validation']) !!}
                    @include('master.room._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/room/edit.blade.php
@extends('adminlte::page')

@section('title', 'Plant - Manufacturing 4.0')

@section('content_header')
    <h1>Plant</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Plant</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">MASTER</li>
                <li class="breadcrumb-item"><a href="{{ route('plant.index') }}">Room</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::model($room, ['url' => route('room.update', $room->id),
                'method' => 'put' , 'id' => 'form_validation']) !!}
                @include('master.room._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/room/index.blade.php
@extends('adminlte::page')

@section('title', 'Room - Meeting Booking')

@section('content_header')
    <h1>Room</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Room</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">MASTER</li>
                <li class="breadcrumb-item active">Room</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    
    @if(session()->has('flash_notification.message'))
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="body">
                @if(session()->get('flash_notification.level') == 'danger')
                <div style="background-color:red" class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @else
                <div class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @endif
            </div>
        </div>
    </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default color-palette-box">
                <div class="card-body">
                    <div class="table-responsive">
                        {!! $dataTable->table(['class' => 'display nowrap table table-hover table-striped', 'width' => '100%']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    {!! $dataTable->scripts() !!}
    <!-- <script> console.log('Hi!'); </script> -->
@stop